openam:
  client:
    clientId: guestbook
    clientSecret: guestbook
    accessTokenUri: http://myapp.forge:8080/openam/oauth2/access_token
    userAuthorizationUri: http://myapp.forge:8080/openam/oauth2/authorize
    tokenName: access_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: openid email profile
  resource:
    userInfoUri: http://myapp.forge:8080/openam/oauth2/userinfo

logging:
  level:
    org.springframework.security: DEBUG